name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Build Docker image
      run: |
        docker build -t my-app .

    - name: Push Docker image
      uses: docker/setup-buildx-action@v2
      with:
        push: true
        tags: my-app:latest
    - name: Deploy with Helm
      run: |
        helm upgrade --install my-release helm/ --values helm/values.yaml
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Deployment complete.\"}" https://hooks.slack.com/services/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

